name: Check Black formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
      - uses: psf/black@stable
        with:
          options: "-l 79 --check"
          src: "."
