name: Pull request
on:
  pull_request:
    branches: [ main ]
jobs:
  check-version:
    name: Check versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Check version number has been properly updated
        run: ".github/is-version-number-acceptable.sh"
